### ISSUE TITLE
Set static IP

### ISSUE THREAD

**Issue by d13r** [d13r/pi-gateway#8]

**Comment by d13r** [comment]
Set with `set-hostname pi.djm.me` (script from dotfiles).

**Comment by d13r** [comment]
Configured in `/etc/netplan/99-custom.yaml`:

```yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - 10.0.0.2/16
      routes:
        - to: default
          via: 10.0.0.1
      nameservers:
        addresses:
          - 1.1.1.1
          - 1.0.0.1
```

Applied with:

```bash
sudo chmod 600 /etc/netplan/99-custom.yaml
sudo netplan try
```

Ignore the warning [`Cannot call Open vSwitch: ovsdb-server.service is not running.`](https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/2041727).
